  - name: install python libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - PyMySQL
    - cryptography

  - name: install mysql
    ansible.builtin.package:
      name: mysql-server
      state: installed  # state must be one of: absent, installed, latest, present, removed

  - name: start mysql service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: connect to mysql server
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_password }}"
      login_host: "mysql.dawscloud.tech"
    register: mysql_info
    ignore_errors: true

  - name: print mysql_info
    ansible.builtin.debug:
      msg: "{{ mysql_info }}"

  - name: setup root password
    ansible.builtin.command: " mysql_secure_installation --set-root-pass ExpenseApp@1"
    when: mysql_info.failed is true